# Setup
title: 문짱구의 게임 개발 블로그
description: Game Programmer
url: https://munjjang9.github.io/
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: munjjang9
  card: summary
logo: logo.png
social:
  name: Sanghee Mun
  links:
    - https://x.com/duke_mun
    - https://github.com/munjjang9
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: munjjang9
  url: https://github.com/munjjang9/
  email: munzzang9@gmail.com

# Code block
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM


# repository 등록확인 
repository               : munjjang9/munjjang9.github.io 

# comments 사용함으로 변경
comments:
  provider               : giscus       # provider : false -> giscus

  giscus:
    repo_id              : <giscus.app_my_configration_repo_id> # https://giscus.app
    category_name        : General 
    category_id          : <giscus.app_my_configration_category_id> 
    discussion_term      : pathname 
    reactions_enabled    : '1' 
    theme                : light 


# post 기본설정에서도 commments 사용함으로 변경 
# comments: false -> comments: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      classes: wide
      read_time: false
      show_date : true 
      comments: true
      related: true